StringTime = Time
StringStart = Click here to start this game!
StringEnd = Congratulation!
StringClick = Clicks
StringTotal = Score
StringScoreEscape = NEXT
StringRanking = HiScore
StringRankingMessage1 = Please type your name
StringRankingMessage2 = and press [ENTER] to entry!
StringRankingEscape = CANCEL
StringRankingNext = NEXT
StringHiScoreEscape = RETURN
ScoreClickPenalty = 5
ScoreTimePenalty = 1
ScoreBase = 3000
MaximumRankingNumber = 11
UpdateKey = 1019
SoundMove = shelfclosea@11.au
SoundEnd = churcha@08.au
TimeToChangeHiScore = 10
TimeToReloadHiScore = 60
DebugLevel = 0
Column = 4
Row = 4
Image = gallaxy.jpg
FontFamily = Monospace
FontSize = 12
ChooseImageFile = Choose Image File
Exit = Exit